workspace = {members = ["practice", "abc189", "abc180", "abc178", "abc170"],exclude = []}
[package]
name = "RustCoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
